services:
  postgres:
    image: postgres:18-alpine
    container_name: ecommerce_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGGRES_PASSWORD: 1234
      POSRGRES_DB: ecommerce_db

    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: